# Generated by Django 3.2.25 on 2024-10-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_promocodeexpiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='promo_code_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
