# Generated by Django 3.2.25 on 2024-10-24 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$GMBINgVPS2krzIKHuCc2eC$N/VXs5U3T4KtpoLMhLi3AyBZanDiWlrCgu6/IUztTbk=', max_length=128),
        ),
    ]
