# Generated by Django 3.2.25 on 2024-10-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='reviews',
        ),
    ]
