# Generated by Django 3.2.25 on 2024-10-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_auto_20241025_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='photo',
        ),
    ]
