# Generated by Django 3.2.25 on 2024-10-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='owner_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
