# Generated by Django 3.2.25 on 2024-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0012_review_owner_response'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['restaurant'], name='restaurants_restaur_52838c_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user'], name='restaurants_user_id_374b6d_idx'),
        ),
        migrations.AlterModelTable(
            name='review',
            table='restaurants_review',
        ),
    ]
